version: '3'
services:
  frontend:
    build: ./client
    restart: always
    ports: 
      - '3000:3000'
  backend:
    build: './backend/'
    restart: always
    ports:
      - '4000:4000'
  database:
    image: mongo
    restart: always
    