version: '3'
services:
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - 5000:80
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: always
    links:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017