version: '3'
services:
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - frontend
      - database
      - backend
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    links:
      - database
    depends_on:
      - database
    restart: always
    volumes:
      - /images
  database:
    image: mongo
    restart: always
    volumes:
      - /data/db