type Query {
    recentEvents(courses: [ID!]): [Event!]!
    event(id: ID!, courses: [ID!]): Event!
    user(id: ID!): User!
    login(email: String!, password: String!): String!
}

type Mutation {
    createUser(userInput: UserInput!): String!
    createEvent(eventInput: EventInput!): Event!
    deleteEvent(eventId: ID!): Boolean!
    addGps(courseId: ID! userRecordingInput: UserRecordingInput!): Boolean!
    removeGps(courseId: ID!): Boolean!
    follow(id: ID!): Boolean!
    unfollow(id: ID!): Boolean!
}